feat: SS-96 Initial draft of system boundaries
lilweege/SyntaxSentinels pull request #115
Opened 2024-10-18 19:45 UTC by N4T10N01

# GitHub Ticket / Description

[SS-96](https://github.com/lilweege/SyntaxSentinels/issues/96)

## Type && Checklist

- [x] **New feature (new APIs, new functional methods)**
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)
- [ ] **Refactoring / Enhancement**
  - [ ] This is breaking change
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)
- [ ] **Bug-fix**
  - [ ] Type:
    - [ ] Code Issue:
    - [ ] Business Logic Issue:
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)

## Dependency

[Are there any required updates which cannot be done in this repo, or must be done after completing this PR?]

## Choose proper operation and replace the \<placeholder\>: `+semver:<placeholder>`

`breaking` `major` `feature` `minor` `fix` `patch`

+semver:patch

2024-10-18 19:47 UTC, lilweege commented
If you used draw.io or another vector graphics program, please upload the source file so it can be edited.

2024-10-21 21:27 UTC, N4T10N01 reviewed
Going to add some definitions and assumptions here for specifying what we are owning as our system. Will align this with other sections too.

2024-10-25 16:19 UTC, lilweege requested changes

2024-10-25 16:19 UTC, lilweege commented on docs/HazardAnalysis/HazardAnalysis.tex
> +Diagram shows referential relationships, not workflows. System Boundary above surrounds all components our team will maintain and accept responsibility. A machine above is a server suitable to host c
```suggestion
Diagram shows referential relationships, not workflows. System Boundary above surrounds all components our team will maintain and accept responsibility. A machine above is a server suitable to host code specified. Any machine mentioned above will not be provided to users from our project, they are expected to be self-hosted either on the user's own servers, or through technology such as Amazon Web Services (AWS) or Microsoft Azure.
```

2024-10-25 16:19 UTC, lilweege commented on docs/SRS-Volere/SRS.tex
> +            \item \textbf{Server Deployment}: Julian will pursue online articles to learn this. He finds maintaining attention for long YouTube videos can be cumbersome and if he's interrupted, it's
Please also rebuild the pdf for this file

2024-10-25 16:20 UTC, lilweege commented
Also make sure you merge the latest HazardAnalysis.pdf

2024-10-25 20:15 UTC, lucasichen approved these changes

2024-10-25 21:10 UTC, lilweege approved these changes
lgtm

2024-10-25 21:10 UTC, lilweege commented on docs/SRS-Volere/SRS.tex
> +            \item \textbf{Server Deployment}: Julian will pursue online articles to learn this. He finds maintaining attention for long YouTube videos can be cumbersome and if he's interrupted, it's
There is still no pdf for this

2024-10-25 21:23 UTC, merged