First draft for Problem Statement and Goals
lilweege/SyntaxSentinels pull request #7
Opened 2024-09-23 19:05 UTC by lilweege

# GitHub Ticket / Description

[SS-5](https://github.com/lilweege/SyntaxSentinels/issues/5)

## Type && Checklist

- [x] **New feature (new APIs, new functional methods)**
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)
- [ ] **Refactoring / Enhancement**
  - [ ] This is breaking change
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)
- [ ] **Bug-fix**
  - [ ] Type:
    - [ ] Code Issue:
    - [ ] Business Logic Issue:
  - [ ] Created (or updated) unit test cases (if required)
  - [ ] Passed unit testing for **ALL** cases
  - [ ] Created (or updated) E2E cases (if required)
  - [ ] Passed E2E testing for **ALL** cases (local or/and sandbox)

## Dependency

[Are there any required updates which cannot be done in this repo, or must be done after completing this PR?]

## Choose proper operation and replace the \<placeholder\>: `+semver:<placeholder>`

`breaking` `major` `feature` `minor` `fix` `patch`

+semver:patch

2024-09-23 23:50 UTC, lucasichen commented
marking this as draft until doc is completed

2024-09-24 20:30 UTC, MohammadMohsinKhan commented
Looks like there's a blank page on page 2. Goals look good to me except for the random extra content in the content which needs to be cleaned up.

2024-09-25 01:25 UTC, lucasichen requested changes

2024-09-25 01:28 UTC, N4T10N01 commented on docs/ProblemStatementAndGoals/ProblemStatement.tex
> +    not simple  by any standards. Figuring out what we are doing and ensuring
I checked, it seems so. Now deleted.

2024-09-25 01:29 UTC, lucasichen approved these changes

2024-09-25 01:59 UTC, MohammadMohsinKhan reviewed
LGTM

2024-09-25 02:00 UTC, MohammadMohsinKhan approved these changes

2024-09-25 02:00 UTC, merged